Repository CaenCamp/jobs-caen-camp, pull requests merged in 2020-04, with the labels that each got.

#53 feature/job-posting-list
  apps/front/public/fonts/icofont.eot
  apps/front/public/fonts/icofont.svg
  apps/front/public/fonts/icofont.ttf
  apps/front/public/fonts/icofont.woff
  apps/front/public/fonts/icofont.woff2
  apps/front/public/global.css
  apps/front/public/icofont.min.css
  apps/front/public/index.html
  apps/front/src/app.svelte
  apps/front/src/components/index.js
  apps/front/src/components/job-postings/index.js
  apps/front/src/components/job-postings/job-posting-card.svelte
  apps/front/src/routes/job-postings.svelte
  apps/front/tailwind.config.js
Labels: RFR, front

#51 chore: make admin app workspaces compliant
  Makefile
  apps/admin/.env
  apps/admin/.gitignore
  apps/admin/README.md
  apps/admin/package.json
  apps/admin/public/favicon.ico
  apps/admin/public/index.html
  apps/admin/public/robots.txt
  apps/admin/src/App.js
  apps/admin/src/App.test.js
  apps/admin/src/index.js
  apps/admin/src/job-posting/Create.js
  apps/admin/src/job-posting/Edit.js
  apps/admin/src/job-posting/List.js
  apps/admin/src/job-posting/index.js
  apps/admin/src/jobBoardDataProvider.js
  apps/admin/src/organization/Create.js
  apps/admin/src/organization/Edit.js
  apps/admin/src/organization/List.js
  apps/admin/src/organization/index.js
  apps/admin/src/setupTests.js
  docker-compose.yml
  not-in-yarn-workspace/admin/package-lock.json
  not-in-yarn-workspace/admin/src/App.test.js
  not-in-yarn-workspace/admin/src/job-posting/index.js
  yarn.lock
Labels: RFR

#58 chore: Add storybook
  .github/CONTRIBUTING.md
  Makefile
  README.md
  apps/front/.storybook/main.js
  apps/front/package.json
  apps/front/stories/button.svelte
  apps/front/stories/index.stories.js
  docker-compose.yml
  yarn.lock
Labels: RFR, front

#63 Reorganize eslint and prettier
  .editorconfig
  .eslintignore
  .eslintrc.json
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .github/workflows/test.yml
  .gitignore
  .prettierignore
  .prettierrc
  Makefile
  apps/admin/.eslintrc.json
  apps/admin/package.json
  apps/api/.eslintrc.json
  apps/api/.prettierrc
  apps/api/package.json
  apps/front/.eslintrc.json
  apps/front/.prettierrc
  apps/front/package.json
  apps/front/public/.gitignore
  apps/front/stories/index.stories.js
  package.json
  tests-e2e/.eslintrc.json
  tests-e2e/.prettierrc
  tests-e2e/package.json
  yarn.lock
Labels: RFR, improvement

#62 Refactor api pagination
  .vscode/extensions.json
  .vscode/settings.json
  apps/admin/src/jobBoardDataProvider.js
  apps/api/openapi/openapi.yaml
  apps/api/package.json
  apps/api/src/index.js
  apps/api/src/job-posting/repository.js
  apps/api/src/job-posting/router.js
  apps/api/src/organization/repository.js
  apps/api/src/organization/router.js
  apps/api/src/toolbox/sanitizers.js
  apps/api/src/toolbox/sanitizers.spec.js
  doc/adr/README.md
  doc/adr/ccc-jb-005-utilisation-de-paramètres-distincts-pour-la-pagination.md
  doc/adr/ccc-jb-006-remplacement-de-l'en-tête-content-range-par-x-total-count-et-link.md
  tests-e2e/api/job-postings.spec.js
  tests-e2e/api/organizations.spec.js
Labels: RFR

#64 Mise à jour des tests pour l'en-tête Link
  tests-e2e/api/job-postings.spec.js
  tests-e2e/api/organizations.spec.js
Labels: RFR

#66 Refactor api sort
  apps/admin/src/jobBoardDataProvider.js
  apps/api/openapi/openapi.yaml
  apps/api/src/job-posting/repository.js
  apps/api/src/job-posting/router.js
  apps/api/src/organization/repository.js
  apps/api/src/organization/router.js
  apps/api/src/toolbox/sanitizers.js
  apps/api/src/toolbox/sanitizers.spec.js
  doc/adr/README.md
  doc/adr/ccc-jb-007-utilisation-de-paramètres-distincts-pour-le-tri.md
  tests-e2e/api/job-postings.spec.js
  tests-e2e/api/organizations.spec.js
Labels: RFR

#61 Sécurisation de l’administration
  .eslintignore
  .github/CONTRIBUTING.md
  Makefile
  README.md
  apps/admin/package.json
  apps/admin/src/App.js
  apps/admin/src/authProvider.js
  apps/admin/src/inMemoryJWT.js
  apps/admin/src/jobBoardDataProvider.js
  apps/api/cli/create-user.js
  apps/api/migrations/20200307072349_creation-table-job_posting.js
  apps/api/migrations/20200410065709_user_account.js
  apps/api/migrations/20200428102341_refresh-token.js
  apps/api/openapi/openapi.yaml
  apps/api/package.json
  apps/api/src/config.js
  apps/api/src/index.js
  apps/api/src/job-posting/router.js
  apps/api/src/organization/router.js
  apps/api/src/toolbox/authentication/jwtMiddleware.js
  apps/api/src/toolbox/authentication/refreshTokenRepository.js
  apps/api/src/toolbox/authentication/router.js
  apps/api/src/user-account/repository.js
  apps/api/src/user-account/user.js
  apps/api/src/user-account/user.spec.js
  config/test.env
  doc/adr/README.md
  doc/adr/ccc-jb-007-utilisation-de-paramètres-distincts-pour-le-tri.md
  doc/adr/ccc-jb-008-securisation-de-l-administration.md
  tests-e2e/api/authentication.spec.js
  tests-e2e/api/job-postings.spec.js
  tests-e2e/api/organizations.spec.js
  yarn.lock
Labels: RFR

#67 Rendre accessible publiquement une partie de l'administration (suite de #61)
  apps/admin/src/App.js
  apps/admin/src/LoginPage.js
  apps/admin/src/LogoutButton.js
  apps/admin/src/authProvider.js
  apps/admin/src/job-posting/List.js
  apps/admin/src/organization/List.js
Labels: RFR
