Repository CaenCamp/jobs-caen-camp, pull requests merged in 2020-03, with the labels that each got.

#25 Mise en place d'OpenAPI
  .github/CONTRIBUTING.md
  Makefile
  README.md
  apps/api-mocked/package.json
  apps/api/openapi/openapi.json
  apps/api/openapi/openapi.yaml
  apps/api/package.json
  apps/front/package.json
  docker-compose.yml
  package.json
  yarn.lock
Labels: RFR

#31 Ajout d'un serveur de mock reposant sur le contrat OpenAPI [Follow #25]
  apps/api/openapi/openapi.json
  apps/api/openapi/openapi.yaml
  docker-compose.yml
Labels: RFR

#32 Proposition de mise en place des ADR.s
  .adr.json
  .github/CONTRIBUTING.md
  .github/adr-list.png
  .github/workflows/test.yml
  Makefile
  doc/adr/README.md
  doc/adr/ccc-jb-001-utiliser-les-adrs-pour-documenter-le-projet.md
  package.json
  yarn.lock
Labels: RFR

#33 Persistance des données
  .github/CONTRIBUTING.md
  .github/workflows/test.yml
  .gitignore
  .vscode/settings.json
  Makefile
  README.md
  apps/api-mocked/package.json
  apps/api/cli/load-fixed-fixtures.js
  apps/api/fixtures/fixed-fixtures.json
  apps/api/knexfile.js
  apps/api/migrations/20200306072137_init-db.js
  apps/api/migrations/20200306082137_creation-table-organization.js
  apps/api/migrations/20200307072349_creation-table-job_posting.js
  apps/api/openapi/openapi.json
  apps/api/openapi/openapi.yaml
  apps/api/package.json
  apps/api/src/config.js
  apps/front/package.json
  config/development.dist
  config/test.env
  doc/adr/README.md
  doc/adr/ccc-jb-001-utiliser-les-adrs-pour-documenter-le-projet.md
  doc/adr/ccc-jb-002-utilisation-de-postgresql-pour-la-persistance-des-donnees.md
  doc/adr/ccc-jb-003-utilisation-de-knex-comme-query-builder.md
  docker-compose-test.yml
  docker-compose.yml
  package.json
  yarn.lock
Labels: RFR

#35 Mise à jour des dépendances
  apps/api/package.json
  apps/front/package.json
  package.json
  yarn.lock
Labels: RFR

#34 API : Première implémentation
  .github/CONTRIBUTING.md
  Makefile
  README.md
  apps/api-mocked/README.md
  apps/api-mocked/index.js
  apps/api-mocked/package.json
  apps/api/fixtures/fixed-fixtures.json
  apps/api/fixtures/generators/job.js
  apps/api/fixtures/generators/organization.js
  apps/api/knexfile.js
  apps/api/openapi/openapi.json
  apps/api/openapi/openapi.yaml
  apps/api/package.json
  apps/api/src/index.js
  apps/api/src/job-posting/repository.js
  apps/api/src/job-posting/repository.spec.js
  apps/api/src/job-posting/router.js
  apps/api/src/organization/repository.js
  apps/api/src/organization/repository.spec.js
  apps/api/src/organization/router.js
  apps/api/src/toolbox/middleware/db.js
  apps/api/src/toolbox/sanitizers.js
  apps/api/src/toolbox/sanitizers.spec.js
  doc/adr/README.md
  doc/adr/ccc-jb-004-oas3-validation-endpoints.md
  docker-compose-test.yml
  docker-compose.yml
  package.json
  tests-e2e/api/index.spec.js
  tests-e2e/api/job-postings.spec.js
  tests-e2e/api/organizations.spec.js
  tests-e2e/package.json
  yarn.lock
Labels: RFR

#36 Mise en place d'une administration
  .github/CONTRIBUTING.md
  Makefile
  README.md
  apps/api/openapi/openapi.yaml
  apps/api/package.json
  apps/api/src/index.js
  apps/api/src/job-posting/repository.js
  docker-compose.yml
  not-in-yarn-workspace/admin/.gitignore
  not-in-yarn-workspace/admin/README.md
  not-in-yarn-workspace/admin/package-lock.json
  not-in-yarn-workspace/admin/package.json
  not-in-yarn-workspace/admin/public/favicon.ico
  not-in-yarn-workspace/admin/public/index.html
  not-in-yarn-workspace/admin/public/robots.txt
  not-in-yarn-workspace/admin/src/App.js
  not-in-yarn-workspace/admin/src/App.test.js
  not-in-yarn-workspace/admin/src/index.js
  not-in-yarn-workspace/admin/src/job-posting/Create.js
  not-in-yarn-workspace/admin/src/job-posting/Edit.js
  not-in-yarn-workspace/admin/src/job-posting/List.js
  not-in-yarn-workspace/admin/src/job-posting/index.js
  not-in-yarn-workspace/admin/src/jobBoardDataProvider.js
  not-in-yarn-workspace/admin/src/organization/Create.js
  not-in-yarn-workspace/admin/src/organization/Edit.js
  not-in-yarn-workspace/admin/src/organization/List.js
  not-in-yarn-workspace/admin/src/organization/index.js
  not-in-yarn-workspace/admin/src/setupTests.js
  package.json
  yarn.lock
Labels: RFR

#37 Revue des ADR
  doc/adr/ccc-jb-001-utiliser-les-adrs-pour-documenter-le-projet.md
  doc/adr/ccc-jb-002-utilisation-de-postgresql-pour-la-persistance-des-donnees.md
  doc/adr/ccc-jb-003-utilisation-de-knex-comme-query-builder.md
  doc/adr/ccc-jb-004-oas3-validation-endpoints.md
Labels: RFR

#49 Réparation du make install
  Makefile
Labels: RFR, bug

#50 Use shell command instead of native cp to fix issues
  Makefile
Labels: RFR, docker

#29 Mise en place de stores pour svelte
  apps/front/jest.config.js
  apps/front/src/app.spec.js
  apps/front/src/app.svelte
  apps/front/src/components/App.svelte
  apps/front/src/components/Company.svelte
  apps/front/src/main.js
  apps/front/src/routes/index.js
  apps/front/src/routes/job-posting.svelte
  apps/front/src/routes/job-postings.svelte
  apps/front/src/routes/organization.svelte
  apps/front/src/routes/organizations.svelte
  apps/front/src/store/index.js
  apps/front/src/store/job-posting.js
  apps/front/src/store/job-postings.js
  apps/front/src/store/organization.js
  apps/front/src/store/organizations.js
  apps/front/webpack.config.js
Labels: WIP

#52 Ajout de Tailwind dans Svelte
  apps/front/package.json
  apps/front/postcss.config.js
  apps/front/src/app.svelte
  apps/front/src/utils/tailwind-css.svelte
  apps/front/tailwind.config.js
  apps/front/webpack.config.js
  yarn.lock
Labels: RFR
